name: PetMate CI Pipeline

on:
  push:
    branches: [ develop ] # Trigger workflow on pushes to the 'develop' branch
  pull_request:
    branches: [ main ] # Trigger on pull requests targeting 'main' (optional)

jobs:
  build_and_test:
    runs-on: ubuntu-latest # Use a Linux runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to get your code

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Match the Java version in your pom.xml
        distribution: 'temurin' # Popular Java distribution
        cache: maven # Cache Maven dependencies to speed up builds

    - name: Build and Test with Maven
      run: mvn clean install # Runs clean, compile, test, package, install phases
